import Image from "next/image";
import Link from "next/link";

const navigation = ["Accueil", "Recherche", "Bibliothèque", "Découvrir", "Favoris", "Amis", "Statistiques"];
const routes = { Accueil: "/", Recherche: "/recherche", Bibliothèque: "/bibliotheque", Découvrir: "/decouverte", Favoris: "/favoris", Amis: "/amis", Statistiques: "/statistiques" };
const releases = [["Divide", "2017 · Album", "from-[#25a6dd] to-[#094664]"], ["X", "2015 · Album", "from-[#21b55b] to-[#102517]"], ["No.6", "2019 · Album", "from-[#f7f3ed] to-[#242424]"], ["Equals", "2021 · Album", "from-[#e5452e] to-[#551819]"], ["Peru", "Dernières sorties", "from-[#e58b70] to-[#476d59]"], ["Multiply", "2014 · Album", "from-[#13a84a] to-[#053719]"]];
const songs = [["Shiver", "1,952,015,881", "3:27", "from-[#e5452e] to-[#551819]"], ["Shape of You", "3,024,067,930", "4:07", "from-[#25a6dd] to-[#094664]"], ["Bad Habits", "2,103,117,355", "3:51", "from-[#303030] to-[#111111]"]];
const played = ["Perfect", "Roman Picisan", "Tittle (Deluxe)", "Shiver", "Feel Something", "Shape of You"];

function Icon({ name }) { const common = { className: "h-5 w-5", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", strokeWidth: "1.8" }; const icons = { Accueil: <path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1V10Z" />, Recherche: <><circle cx="11" cy="11" r="6.5" /><path d="m16 16 4.5 4.5" /></>, Bibliothèque: <><rect x="4" y="3" width="16" height="18" rx="2" /><path d="M8 3v5l2-1.5L12 8V3" /></>, Découvrir: <><circle cx="12" cy="12" r="9" /><path d="m15.5 8.5-2.2 4.8-4.8 2.2 2.2-4.8 4.8-2.2Z" /></>, Favoris: <path d="M20.8 8.8c0 5.1-8.8 10.2-8.8 10.2S3.2 13.9 3.2 8.8A4.8 4.8 0 0 1 12 6a4.8 4.8 0 0 1 8.8 2.8Z" />, Amis: <><circle cx="9" cy="8" r="3" /><path d="M3.5 20c.4-3.4 2.3-5 5.5-5s5.1 1.6 5.5 5M17 9a2.5 2.5 0 1 0 0-5M17 15c2.1 0 3.3 1.1 3.7 3.2" /></>, Statistiques: <path d="M4 20V11M10 20V4M16 20v-7M22 20V8" /> }; return <svg {...common}>{icons[name]}</svg>; }
function Cover({ gradient, className = "" }) { return <div className={`relative shrink-0 overflow-hidden rounded-lg bg-gradient-to-br ${gradient} ${className}`}><div className="absolute -right-5 -top-6 h-20 w-20 rounded-full border-[14px] border-white/15" /><div className="absolute inset-x-0 bottom-0 h-1/3 bg-black/25" /></div>; }

export default function DecouvertePage() { return <main className="min-h-screen bg-black text-[#edf0ff] lg:flex">
  <aside className="sticky top-[70px] hidden h-[calc(100dvh-70px)] w-64 shrink-0 self-start overflow-y-auto border-r border-[#5d72fe]/20 bg-[#03050b] px-7 py-6 lg:flex lg:flex-col"><Link href="/" className="mb-9 flex items-center gap-3"><Image src="/logoAudiva2.png" alt="Audiva" width={1254} height={1254} className="h-12 w-12 rounded-xl object-cover" /><span className="text-2xl font-semibold tracking-tight">Audi<span className="text-[#5d72fe]">va</span></span></Link><nav className="space-y-1">{navigation.map((item) => <Link key={item} href={routes[item]} className={`flex items-center gap-4 rounded-xl px-3 py-3 text-sm ${item === "Découvrir" ? "bg-[#5d72fe] font-semibold text-white" : "text-[#b9c2ed] hover:bg-[#5d72fe]/10 hover:text-white"}`}><Icon name={item} />{item}</Link>)}</nav></aside>
  <div className="min-w-0 flex-1 pb-12"><div className="grid gap-5 p-5 sm:p-7 xl:grid-cols-[minmax(0,1fr)_270px]">
    <div><div className="mb-5 flex items-center gap-3 text-sm text-[#9aa5d6]"><span>Accueil</span><span>›</span><span className="text-white">Artiste populaire</span></div><section className="relative min-h-[245px] overflow-hidden rounded-xl border border-[#5d72fe]/25 bg-[radial-gradient(circle_at_72%_35%,rgba(93,114,254,0.5),transparent_28%),linear-gradient(135deg,#07151c,#0a1f2b_55%,#10102b)] p-6 sm:p-8"><div className="absolute right-8 top-5 hidden h-64 w-48 rounded-t-[90px] bg-gradient-to-b from-[#eeb27d] via-[#b7724a] to-[#2a303a] opacity-90 md:block" /><div className="relative"><p className="flex items-center gap-2 text-sm text-[#bdc6f5]"><span className="text-[#5d72fe]">✦</span> Artiste vérifié</p><h1 className="mt-4 text-4xl font-bold sm:text-5xl">Ed Sheeran</h1><p className="mt-5 text-sm text-[#c4cae7]">◉ &nbsp; 82,736,050 auditeurs mensuels</p><div className="mt-6 flex gap-3"><button className="rounded-full bg-[#5d72fe] px-6 py-3 text-sm font-bold hover:bg-[#7184ff]">PLAY</button><button className="rounded-full border border-white/70 px-5 py-3 text-sm font-semibold">✓ &nbsp; SUIVI</button></div></div></section>
      <Section title="Sorties populaires"><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{releases.map(([name, detail, gradient]) => <article key={name}><Cover gradient={gradient} className="aspect-square w-full" /><p className="mt-2 text-sm font-medium">{name}</p><p className="mt-1 truncate text-[10px] text-[#8f9bc9]">{detail}</p></article>)}</div></Section>
      <Section title="Chansons populaires"><div className="space-y-1">{songs.map(([title, streams, duration, gradient], index) => <div key={title} className="grid grid-cols-[24px_minmax(180px,1fr)_minmax(110px,0.7fr)_55px_30px] items-center gap-3 rounded-md p-2 text-sm hover:bg-[#5d72fe]/10"><span className="text-[#aab5e5]">{index + 1}</span><div className="flex items-center gap-3"><Cover gradient={gradient} className="h-12 w-12" /><span className={index === 1 ? "font-semibold text-[#7184ff]" : "font-semibold"}>{title}</span></div><span className="hidden text-xs text-[#aab5e5] sm:block">◉ &nbsp; {streams}</span><span className="text-xs">◷ &nbsp;{duration}</span><span className="text-lg">♡</span></div>)}</div></Section>
    </div>
    <aside className="rounded-xl border border-[#5d72fe]/20 bg-[#0a0e1a] p-4"><div className="flex items-center justify-between"><h2 className="font-semibold">Fans aiment aussi</h2><button className="text-xs text-[#7184ff]">Voir tout</button></div><Cover gradient="from-[#e5e5e5] via-[#777] to-[#171717]" className="mt-4 h-48 w-full" /><p className="mt-3 text-sm font-semibold">James Arthur</p><p className="text-xs text-[#8f9bc9]">Artiste</p><div className="mt-7 flex items-center justify-between"><h2 className="font-semibold">Écoutés récemment</h2><button className="text-xs text-[#7184ff]">Voir tout</button></div><div className="mt-4 space-y-3">{played.map((title, index) => <div key={title} className="flex items-center gap-3"><Cover gradient={releases[index % releases.length][2]} className="h-10 w-10" /><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold">{title}</p><p className="mt-1 text-[10px] text-[#8f9bc9]">Ed Sheeran</p></div><span className="text-[10px] text-[#8f9bc9]">{index + 2}h</span></div>)}</div></aside>
  </div></div>
</main>; }

function Section({ title, children }) { return <section className="mt-8"><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-semibold">{title}</h2><button className="text-xs text-[#7184ff]">Voir tout</button></div>{children}</section>; }
