"use client";

import Image from "next/image";
import Link from "next/link";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { HugeiconsIcon } from "@hugeicons/react";
import { AddToListIcon, ArrowLeft01Icon, ArrowRight01Icon, FavouriteIcon, MoreHorizontalIcon, PlayIcon, Queue01Icon } from "@hugeicons/core-free-icons";
import { topAlbums, topArtists, topPlaylists } from "@/domaines/accueil/donnees/accueilMock";
import { demoQueue, useLecteurStore } from "@/domaines/lecteur/stores/lecteurStore";

const chartMoves = ["↑ +3", "NEW", "↑ +1", "— stable"];
const formatDuration = (seconds) => `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, "0")}`;

function IconButton({ label, children, className = "", ...props }) {
  return <button type="button" aria-label={label} title={label} className={`flex h-9 w-9 items-center justify-center rounded-full text-[#b8c4de] transition duration-150 hover:scale-105 hover:bg-white/10 hover:text-white active:scale-90 ${className}`} {...props}>{children}</button>;
}

function SectionTitle({ title, href, children }) {
  return <div className="mb-4 flex items-center justify-between gap-4"><h2 className="text-xl font-extrabold tracking-[-.035em] text-[#f1f5ff]">{title}</h2><div className="flex items-center gap-2">{children}<Link href={href} className="ml-2 text-xs font-bold text-[#91a1c7] transition hover:text-[#76eee9]">Voir tout</Link></div></div>;
}

export function ZoneMusicale() {
  const router = useRouter();
  const albumRail = useRef(null);
  const [openMenu, setOpenMenu] = useState(null);
  const [message, setMessage] = useState("");
  const { currentTrack, isPlaying, likedTrackIds, setCurrentTrack, setQueue, play, toggleLike, addToQueue } = useLecteurStore();
  const notify = (text) => { setMessage(text); window.setTimeout(() => setMessage(""), 2200); };
  const launchTrack = (track) => { setCurrentTrack(track); play(); };
  const playAlbum = (album) => { const tracks = demoQueue.filter((track) => ["blue-hour", "electric-night", "lila-sun", "afro-future"].indexOf(album.id) === demoQueue.findIndex((item) => item.id === track.id)); setQueue(tracks.length ? tracks : demoQueue); launchTrack((tracks.length ? tracks : demoQueue)[0]); };
  const playPlaylist = (playlist) => { const tracks = playlist.trackIds.map((id) => demoQueue.find((track) => track.id === id)).filter(Boolean); setQueue(tracks); launchTrack(tracks[0]); notify(`${playlist.title} est chargé dans la file`); };
  const scrollAlbums = (direction) => albumRail.current?.scrollBy({ left: direction * 360, behavior: "smooth" });

  return <section className="relative mx-auto max-w-[1500px] px-4 pb-12 pt-2 sm:px-7">
    <SectionTitle title="Top Albums" href="/bibliotheque/albums"><IconButton label="Albums précédents" onClick={() => scrollAlbums(-1)}><HugeiconsIcon icon={ArrowLeft01Icon} size={19} strokeWidth={2.3} /></IconButton><IconButton label="Albums suivants" onClick={() => scrollAlbums(1)}><HugeiconsIcon icon={ArrowRight01Icon} size={19} strokeWidth={2.3} /></IconButton></SectionTitle>
    <div ref={albumRail} className="audiva-rail -mx-4 flex snap-x gap-4 overflow-x-auto px-4 pb-2 sm:-mx-7 sm:px-7">{topAlbums.map((album) => <article key={album.id} onClick={() => router.push(`/albums/${album.id}`)} className="group relative w-[210px] shrink-0 snap-start cursor-pointer overflow-hidden rounded-2xl bg-[#0c1529] p-2.5 ring-1 ring-white/5 transition duration-300 hover:-translate-y-1 hover:bg-[#12203a] hover:ring-[#76eee9]/35"><Image src={album.cover} alt={`Pochette ${album.title}`} width={420} height={420} className="aspect-square w-full rounded-xl object-cover transition duration-500 group-hover:scale-[1.04]" /><div className="absolute inset-x-2.5 top-2.5 aspect-square rounded-xl bg-gradient-to-t from-[#030914]/75 via-transparent to-transparent opacity-0 transition group-hover:opacity-100" /><div className="absolute right-4 top-4 flex translate-y-1 gap-1 opacity-0 transition duration-200 group-hover:translate-y-0 group-hover:opacity-100"><IconButton label={`Ajouter ${album.title} aux favoris`} onClick={(event) => { event.stopPropagation(); toggleLike(); }} className="bg-[#081426]/80 backdrop-blur"><HugeiconsIcon icon={FavouriteIcon} size={18} /></IconButton><IconButton label="Plus d'actions" onClick={(event) => { event.stopPropagation(); setOpenMenu(openMenu === album.id ? null : album.id); }} className="bg-[#081426]/80 backdrop-blur"><HugeiconsIcon icon={MoreHorizontalIcon} size={19} /></IconButton></div><button type="button" onClick={(event) => { event.stopPropagation(); playAlbum(album); }} aria-label={`Lire ${album.title}`} className="absolute bottom-[70px] right-5 flex h-11 w-11 translate-y-2 items-center justify-center rounded-full bg-[#76eee9] text-[#04121f] opacity-0 shadow-lg transition duration-200 group-hover:translate-y-0 group-hover:opacity-100 hover:scale-110 active:scale-90"><HugeiconsIcon icon={PlayIcon} size={21} fill="currentColor" /></button><div className="px-1 pb-1 pt-3"><h3 className="truncate text-sm font-extrabold">{album.title}</h3><p className="mt-1 truncate text-xs font-medium text-[#91a0c0]">{album.artist}</p><p className="mt-1 text-[11px] text-[#657493]">{album.tracks} chansons</p></div></article>)}</div>

    <div className="mt-10 grid gap-8 xl:grid-cols-[minmax(0,1.18fr)_minmax(340px,.82fr)]"><section><SectionTitle title="Top 30" href="/decouverte/tendances" /><div className="overflow-hidden rounded-2xl border border-white/6 bg-[#0a1326]">{demoQueue.map((track, index) => <div key={track.id} onClick={() => launchTrack(track)} className={`group flex cursor-pointer items-center gap-3 border-b border-white/6 px-3 py-2.5 last:border-0 transition hover:bg-white/[.045] ${currentTrack?.id === track.id ? "bg-[#13264a]/70" : ""}`}><span className={`w-5 text-center text-xs font-extrabold ${index === 0 ? "text-[#76eee9]" : "text-[#8b9abd]"}`}>{String(index + 1).padStart(2, "0")}</span><Image src={track.cover} alt="" width={48} height={48} className="h-11 w-11 rounded-lg object-cover" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-extrabold">{track.title}</p><p className="truncate text-xs text-[#91a0c0]">{track.artist}</p></div><span className={`hidden w-14 text-center text-[10px] font-extrabold sm:block ${chartMoves[index].includes("↑") ? "text-[#72e5ad]" : chartMoves[index] === "NEW" ? "text-[#76eee9]" : "text-[#7f8dab]"}`}>{chartMoves[index]}</span><span className="hidden text-xs font-medium text-[#8493b3] sm:block">{formatDuration(track.duration)}</span><IconButton label="Favori" onClick={(event) => { event.stopPropagation(); toggleLike(track); }} className={likedTrackIds.includes(track.id) ? "text-[#76eee9]" : ""}><HugeiconsIcon icon={FavouriteIcon} size={19} fill={likedTrackIds.includes(track.id) ? "currentColor" : "none"} /></IconButton><button type="button" onClick={(event) => { event.stopPropagation(); launchTrack(track); }} className={`flex h-9 w-9 items-center justify-center rounded-full transition hover:scale-110 active:scale-90 ${currentTrack?.id === track.id && isPlaying ? "bg-[#183c56] text-[#76eee9]" : "bg-[#76eee9] text-[#04121f]"}`} aria-label={`Lire ${track.title}`}><HugeiconsIcon icon={PlayIcon} size={18} fill="currentColor" /></button><IconButton label="Actions rapides" onClick={(event) => { event.stopPropagation(); setOpenMenu(openMenu === track.id ? null : track.id); }}><HugeiconsIcon icon={MoreHorizontalIcon} size={19} /></IconButton>{openMenu === track.id && <QuickMenu track={track} onClose={() => setOpenMenu(null)} onQueue={() => { addToQueue(track); notify("Ajouté à la file d’attente"); }} onPlaylist={() => notify("Ajouté à votre playlist Chill & Relax")} onNavigate={(path) => router.push(path)} />}</div>)}</div></section>
      <section><SectionTitle title="Top Artistes" href="/decouverte" /><div className="grid grid-cols-2 gap-3 sm:grid-cols-4 xl:grid-cols-2">{topArtists.map((artist) => <Link href={`/artistes/${artist.id}`} key={artist.id} className="group rounded-2xl bg-[#0a1326] p-3 ring-1 ring-white/6 transition hover:-translate-y-1 hover:bg-[#12203a] hover:ring-[#76eee9]/30"><div className="relative aspect-square overflow-hidden rounded-full"><Image src={artist.image} alt={artist.name} fill sizes="180px" className={`${artist.position} object-cover transition duration-500 group-hover:scale-110`} /><span className="absolute inset-0 bg-gradient-to-t from-[#071428]/65 to-transparent" /></div><p className="mt-3 truncate text-sm font-extrabold">{artist.name}</p><p className="mt-1 truncate text-[11px] font-medium text-[#91a0c0]">{artist.listeners}</p></Link>)}</div></section></div>

    <SectionTitle title="Top Playlists" href="/bibliotheque?vue=playlists" /><div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">{topPlaylists.map((playlist) => <article key={playlist.id} className="group relative overflow-hidden rounded-2xl bg-[#0c1529] p-3 ring-1 ring-white/5 transition hover:-translate-y-1 hover:bg-[#12203a] hover:ring-[#76eee9]/30"><Image src={playlist.cover} alt={playlist.title} width={480} height={300} className="aspect-[1.35] w-full rounded-xl object-cover transition duration-500 group-hover:scale-[1.04]" /><div className="absolute left-5 top-5 rounded-full bg-[#071427]/70 px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-[.12em] text-[#76eee9] backdrop-blur">Playlist</div><button type="button" onClick={() => playPlaylist(playlist)} aria-label={`Lire ${playlist.title}`} className="absolute right-5 top-[138px] flex h-10 w-10 items-center justify-center rounded-full bg-[#76eee9] text-[#04121f] opacity-0 transition group-hover:opacity-100 hover:scale-110 active:scale-90"><HugeiconsIcon icon={PlayIcon} size={20} fill="currentColor" /></button><div className="px-1 pb-1 pt-4"><h3 className="truncate text-sm font-extrabold">{playlist.title}</h3><p className="mt-1 line-clamp-2 text-xs leading-5 text-[#91a0c0]">{playlist.description}</p><div className="mt-3 flex items-center justify-between"><span className="text-[11px] font-bold text-[#7686a7]">{playlist.tracks} titres</span><div className="flex gap-1"><IconButton label="Ajouter aux favoris"><HugeiconsIcon icon={FavouriteIcon} size={18} /></IconButton><IconButton label="Ajouter à la file" onClick={() => { playlist.trackIds.forEach((id) => addToQueue(demoQueue.find((track) => track.id === id))); notify("Playlist ajoutée à la file"); }}><HugeiconsIcon icon={Queue01Icon} size={18} /></IconButton></div></div></div></article>)}</div>
    {message && <div role="status" className="fixed bottom-24 right-5 z-[60] rounded-xl border border-[#76eee9]/25 bg-[#0b1830] px-4 py-3 text-sm font-semibold shadow-2xl">{message}</div>}
  </section>;
}

function QuickMenu({ track, onClose, onQueue, onPlaylist, onNavigate }) {
  const runAction = (action) => () => { action(); onClose(); };
  return <div onClick={(event) => event.stopPropagation()} className="absolute right-3 top-12 z-30 w-52 rounded-xl border border-white/10 bg-[#101b33] p-1.5 shadow-2xl"><button onClick={runAction(onQueue)} className="quick-menu-item"><HugeiconsIcon icon={Queue01Icon} size={17} />Ajouter à la file</button><button onClick={runAction(onPlaylist)} className="quick-menu-item"><HugeiconsIcon icon={AddToListIcon} size={17} />Ajouter à une playlist</button><button onClick={runAction(() => onNavigate(`/artistes/${track.id}`))} className="quick-menu-item">Voir l&apos;artiste</button><button onClick={runAction(() => onNavigate(`/albums/${track.album?.toLowerCase().replaceAll(" ", "-")}`))} className="quick-menu-item">Voir l&apos;album</button><button onClick={onClose} className="quick-menu-item text-[#8d9cb9]">Fermer</button></div>;
}
