import Image from "next/image";
import Link from "next/link";
import { HugeiconsIcon } from "@hugeicons/react";
import { ChartBarBigIcon, LibraryIcon, Message01Icon } from "@hugeicons/core-free-icons";

const profiles = { sophie: { name: "Sophie N.", username: "@sophiewaves", avatar: "/hero-decouverte.jpg", artist: "Lila Sun", playlist: "Afro Future", common: "Afro & Indie" }, marc: { name: "Marc T.", username: "@marcafterdark", avatar: "/hero-tendances.jpg", artist: "Kairo", playlist: "Night Drive", common: "Electro nocturne" }, julie: { name: "Julie R.", username: "@julieonrepeat", avatar: "/hero-recommandation.jpg", artist: "Maya K.", playlist: "Blue Hour", common: "Pop alternative" } };

export default async function AmiDetailPage({ params }) {
  const { id } = await params; const friend = profiles[id] || { name: "Ami Audiva", username: "@audiva", avatar: "/hero-playlist.jpg", artist: "À découvrir", playlist: "Ma sélection", common: "Vos goûts musicaux" };
  return <main className="min-h-screen bg-[#060b18] pb-32 text-[#eff4ff]"><section className="relative isolate overflow-hidden border-b border-white/[.07] bg-[#081122] px-5 pb-10 pt-12 sm:px-10 lg:px-14"><Image src={friend.avatar} alt="" fill priority className="-z-20 scale-110 object-cover opacity-30 blur-sm" /><div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,#060b18_4%,rgba(6,11,24,.76)_55%,#060b18),linear-gradient(180deg,transparent,#060b18)]" /><div className="relative mx-auto flex max-w-[1500px] flex-col items-start gap-5 sm:min-h-[270px] sm:flex-row sm:items-end"><Image src={friend.avatar} alt="" width={150} height={150} className="h-32 w-32 rounded-full object-cover ring-2 ring-[#72eee7] sm:h-40 sm:w-40" /><div className="pb-1"><p className="text-[11px] font-bold uppercase tracking-[.16em] text-[#83eee8]">Profil ami</p><h1 className="mt-2 text-4xl font-black text-white sm:text-6xl">{friend.name}</h1><p className="mt-2 text-sm text-[#c1cce3]">{friend.username} · Goûts communs : {friend.common}</p></div></div></section><section className="mx-auto w-full max-w-[1500px] px-4 py-8 sm:px-7 xl:px-9"><div className="flex flex-wrap gap-3"><Link href={`/chat?conversation=${id}`} className="inline-flex items-center gap-2 bg-[#72eee7] px-5 py-3 text-sm font-extrabold text-[#061426]"><HugeiconsIcon icon={Message01Icon} size={19} />Écrire à {friend.name.split(" ")[0]}</Link><Link href="/bibliotheque?vue=statistiques" className="inline-flex items-center gap-2 border border-white/14 px-5 py-3 text-sm font-extrabold text-white hover:border-[#72eee7]/45"><HugeiconsIcon icon={ChartBarBigIcon} size={19} />Comparer nos statistiques</Link></div><div className="mt-8 grid gap-4 md:grid-cols-3"><article className="border border-white/[.08] bg-[#0a1221] p-5"><p className="text-xs font-bold text-[#91a0bd]">Top artiste</p><p className="mt-3 text-xl font-black">{friend.artist}</p></article><article className="border border-white/[.08] bg-[#0a1221] p-5"><p className="text-xs font-bold text-[#91a0bd]">Playlist publique</p><p className="mt-3 text-xl font-black">{friend.playlist}</p></article><article className="border border-white/[.08] bg-[#0a1221] p-5"><p className="text-xs font-bold text-[#91a0bd]">Compatibilité musicale</p><p className="mt-3 text-xl font-black text-[#72eee7]">86 %</p></article></div><article className="mt-5 flex items-center justify-between border border-white/[.08] bg-[#0a1221] p-5"><div><p className="font-extrabold">Écouter la playlist de {friend.name.split(" ")[0]}</p><p className="mt-1 text-sm text-[#91a0bd]">Une sélection publique basée sur ses écoutes récentes.</p></div><Link href="/bibliotheque?vue=playlists" className="inline-flex items-center gap-2 text-sm font-bold text-[#72eee7]"><HugeiconsIcon icon={LibraryIcon} size={18} />Voir les playlists</Link></article></section></main>;
}
