"use client";

import Image from "next/image";
import { Suspense, useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { HugeiconsIcon } from "@hugeicons/react";
import { Add01Icon, Message01Icon, MusicNote01Icon, SendIcon, Share01Icon } from "@hugeicons/core-free-icons";
import { useLecteurStore } from "@/domaines/lecteur/stores/lecteurStore";
import { useSocialStore } from "@/domaines/social/stores/socialStore";

const Send01Icon = SendIcon;

export default function ChatPage() { return <Suspense fallback={<main className="min-h-screen bg-[#060b18]" />}><Chat /></Suspense>; }
function Chat() {
  useEffect(() => {
    const sections = document.querySelectorAll("main > section");
    const banner = sections[0]; const discussion = sections[1];
    const bannerMessage = document.createElement("p");
    bannerMessage.dataset.audivaMessage = "true";
    bannerMessage.textContent = "Partagez un morceau, une playlist ou simplement ce que la musique vous fait ressentir.";
    bannerMessage.className = "mt-3 max-w-xl text-sm leading-6 text-[#d4def0]";
    const root = banner?.closest("main");
    if (root) { root.style.height = "calc(100dvh - 72px)"; root.style.overflow = "hidden"; root.style.paddingBottom = "0"; }
    if (banner) { banner.style.minHeight = "250px"; banner.style.backgroundImage = "linear-gradient(90deg, rgba(6,11,24,.94) 2%, rgba(6,11,24,.58) 53%, rgba(6,11,24,.24)), url('/message1.jpg')"; banner.style.backgroundPosition = "center"; banner.style.backgroundSize = "cover"; const overlay = banner.querySelector(".absolute"); if (overlay) overlay.style.background = "linear-gradient(180deg, transparent 45%, rgba(6,11,24,.92))"; const copy = banner.querySelector(".mx-auto > div:last-child"); if (copy) copy.appendChild(bannerMessage); }
    if (discussion) { discussion.style.height = "calc(100dvh - 322px)"; discussion.style.marginTop = "0"; discussion.style.marginBottom = "0"; discussion.style.backgroundImage = "linear-gradient(rgba(7,14,27,.84), rgba(7,14,27,.9)), url('/discussions.jpg')"; discussion.style.backgroundPosition = "center"; discussion.style.backgroundSize = "cover"; }
    return () => { bannerMessage.remove(); if (root) { root.style.height = ""; root.style.overflow = ""; root.style.paddingBottom = ""; } if (banner) { banner.style.minHeight = ""; banner.style.backgroundImage = ""; banner.style.backgroundPosition = ""; banner.style.backgroundSize = ""; } if (discussion) { discussion.style.height = ""; discussion.style.marginTop = ""; discussion.style.marginBottom = ""; discussion.style.backgroundImage = ""; discussion.style.backgroundPosition = ""; discussion.style.backgroundSize = ""; } };
  }, []);
  const params = useSearchParams(); const { friends, conversations, sendMessage, markConversationRead, clearConversation } = useSocialStore(); const { currentTrack } = useLecteurStore();
  const requestedId = params.get("conversation"); const first = requestedId || conversations[0]?.id; const [activeId, setActiveId] = useState(first), [text, setText] = useState("");
  const active = useMemo(() => conversations.find((conversation) => conversation.id === (requestedId || activeId)) || conversations[0], [conversations, requestedId, activeId]); const friend = friends.find((item) => item.id === active?.participantId);
  useEffect(() => { if (active?.id) markConversationRead(active.id); }, [active?.id, markConversationRead]);
  useEffect(() => { const header = document.querySelector("main > section:nth-of-type(2) header"); if (!header || !active?.id) return undefined; const button = document.createElement("button"); button.type = "button"; button.textContent = "Effacer l’historique"; button.className = "ml-auto border border-white/12 px-3 py-2 text-xs font-bold text-[#b8c5dc] hover:border-rose-300 hover:text-rose-200"; const onClear = () => clearConversation(active.id); button.addEventListener("click", onClear); header.appendChild(button); return () => { button.removeEventListener("click", onClear); button.remove(); }; }, [active?.id, clearConversation]);
  const select = (id) => { setActiveId(id); markConversationRead(id); };
  const send = (event) => { event.preventDefault(); const value = text.trim(); if (!value || !active) return; sendMessage(active.id, { text: value }); setText(""); };
  const shareTrack = () => { if (!active || !currentTrack) return; sendMessage(active.id, { share: { kind: "morceau", title: currentTrack.title, subtitle: `${currentTrack.artist} · ${currentTrack.album}`, cover: currentTrack.cover } }); };
  const sharePlaylist = () => { if (!active) return; sendMessage(active.id, { share: { kind: "playlist", title: "Ma sélection Audiva", subtitle: "Une playlist créée pour vous", cover: "/hero-playlist.jpg" } }); };
  return <main className="min-h-screen bg-[#060b18] pb-32 text-[#eff4ff]"><section className="relative isolate overflow-hidden border-b border-white/[.07] bg-[#081122] px-5 py-8 sm:px-10 lg:px-14"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_78%_5%,rgba(80,128,255,.28),transparent_35%),linear-gradient(135deg,#071120,#0b1730_58%,#060b18)]" /><div className="mx-auto flex max-w-[1500px] items-center gap-4"><div className="grid h-14 w-14 place-items-center bg-[#102044] text-[#72eee7]"><HugeiconsIcon icon={Message01Icon} size={28} /></div><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-[#83eee8]">Messages privés</p><h1 className="mt-1 text-3xl font-black text-white">Chat entre amis</h1></div></div></section><section className="mx-auto grid w-full max-w-[1500px] overflow-hidden border border-white/[.08] bg-[#0a1221] sm:my-8 sm:min-h-[620px] sm:grid-cols-[280px_minmax(0,1fr)] xl:grid-cols-[330px_minmax(0,1fr)]"><ConversationList conversations={conversations} friends={friends} activeId={active?.id} onSelect={select} />{active && friend ? <Conversation friend={friend} conversation={active} text={text} setText={setText} onSend={send} onTrack={shareTrack} onPlaylist={sharePlaylist} /> : <div className="grid place-items-center p-8 text-center text-[#91a0bd]">Choisissez une conversation.</div>}</section></main>;
}

function ConversationList({ conversations, friends, activeId, onSelect }) { return <aside className="border-b border-white/[.08] sm:border-b-0 sm:border-r"><div className="border-b border-white/[.07] p-4"><p className="font-extrabold text-white">Conversations</p><p className="mt-1 text-xs text-[#91a0bd]">Vos échanges et partages</p></div><div className="flex overflow-x-auto p-2 sm:block sm:space-y-1">{conversations.map((conversation) => { const friend = friends.find((item) => item.id === conversation.participantId); const latest = conversation.messages[conversation.messages.length - 1]; return <button type="button" key={conversation.id} onClick={() => onSelect(conversation.id)} className={`flex min-w-[215px] items-center gap-3 p-3 text-left transition sm:min-w-0 sm:w-full ${activeId === conversation.id ? "bg-[#15294a]" : "hover:bg-white/[.045]"}`}><Avatar friend={friend} /><span className="min-w-0 flex-1"><span className="flex items-center justify-between gap-2"><b className="truncate text-sm text-white">{friend?.name}</b><small className="text-[10px] text-[#71809d]">{conversation.updatedAt}</small></span><span className="mt-1 block truncate text-xs text-[#91a0bd]">{latest?.share ? `Partage : ${latest.share.title}` : latest?.text}</span></span>{conversation.unread ? <span className="grid h-5 min-w-5 place-items-center rounded-full bg-[#72eee7] px-1 text-[10px] font-black text-[#061426]">{conversation.unread}</span> : null}</button>; })}</div></aside>; }
function Conversation({ friend, conversation, text, setText, onSend, onTrack, onPlaylist }) { return <section className="flex min-h-[520px] min-w-0 flex-col"><header className="flex items-center gap-3 border-b border-white/[.07] px-5 py-4"><Avatar friend={friend} /><div><p className="font-extrabold text-white">{friend.name}</p><p className="text-xs text-[#72eee7]">{friend.online ? "En ligne" : "Hors ligne"}</p></div></header><div className="flex-1 space-y-4 overflow-y-auto bg-[#08101e]/60 p-5">{conversation.messages.map((message) => <Message key={message.id} message={message} friend={friend} />)}</div><form onSubmit={onSend} className="border-t border-white/[.07] p-4"><div className="mb-3 flex gap-2"><button type="button" onClick={onTrack} className="inline-flex items-center gap-2 border border-white/12 px-3 py-2 text-xs font-bold text-[#cbd6ea] hover:border-[#72eee7]/45"><HugeiconsIcon icon={MusicNote01Icon} size={16} />Partager le morceau</button><button type="button" onClick={onPlaylist} className="inline-flex items-center gap-2 border border-white/12 px-3 py-2 text-xs font-bold text-[#cbd6ea] hover:border-[#72eee7]/45"><HugeiconsIcon icon={Share01Icon} size={16} />Partager une playlist</button></div><div className="flex items-center gap-2 border border-white/12 bg-[#07101e] p-2 focus-within:border-[#72eee7]/55"><button type="button" className="grid h-9 w-9 place-items-center text-[#91a0bd]"><HugeiconsIcon icon={Add01Icon} size={19} /></button><input value={text} onChange={(event) => setText(event.target.value)} placeholder={`Écrire à ${friend.name}…`} className="min-w-0 flex-1 bg-transparent px-1 text-sm text-white outline-none placeholder:text-[#71809d]" /><button type="submit" disabled={!text.trim()} aria-label="Envoyer" className="grid h-10 w-10 place-items-center bg-[#72eee7] text-[#061426] transition hover:bg-white disabled:opacity-40"><HugeiconsIcon icon={Send01Icon} size={19} /></button></div></form></section>; }
function Message({ message, friend }) { const mine = message.author === "me"; return <div className={`flex ${mine ? "justify-end" : "justify-start"}`}><div className={`max-w-[82%] ${mine ? "bg-[#72eee7] text-[#061426]" : "bg-[#172237] text-[#edf4ff]"}`}>{message.share ? <button type="button" className="block w-full p-2 text-left"><div className="flex items-center gap-3"><span className="relative h-14 w-14 shrink-0 overflow-hidden"><Image src={message.share.cover} alt="" fill sizes="56px" className="object-cover" /></span><span><span className="block text-[10px] font-black uppercase tracking-[.12em] opacity-65">{message.share.kind}</span><b className="mt-1 block text-sm">{message.share.title}</b><span className="mt-1 block text-xs opacity-75">{message.share.subtitle}</span></span></div></button> : <p className="px-3 py-2.5 text-sm">{message.text}</p>}<p className="px-3 pb-2 text-[10px] font-bold opacity-55">{message.time}{mine && " · Lu"}</p></div></div>; }
function Avatar({ friend }) { return <span className="relative h-11 w-11 shrink-0 overflow-hidden rounded-full bg-[#152444]"><Image src={friend?.avatar || "/hero-playlist.jpg"} alt="" fill sizes="44px" className="object-cover" />{friend?.online && <span className="absolute bottom-0.5 right-0.5 h-2.5 w-2.5 rounded-full border-2 border-[#0a1221] bg-[#72eee7]" />}</span>; }
