import Image from "next/image";
import Link from "next/link";

const navigation = [["Accueil", "/"], ["Recherche", "/recherche"], ["Bibliothèque", "/bibliotheque"], ["Découvrir", "/decouverte"], ["Favoris", "/favoris"], ["Amis", "/amis"], ["Statistiques", "/statistiques"]];
const playlists = [["Hits du moment", "32 morceaux · Mise à jour aujourd’hui", "from-[#d44d83] to-[#fa9353]"], ["Afro Vibes", "56 morceaux · Par Audiva", "from-[#d17a32] to-[#302236]"], ["Chill & Relax", "42 morceaux · Pour se détendre", "from-[#6eaec7] to-[#f6e5c5]"], ["Ma playlist", "18 morceaux · Créée par vous", "from-[#6e5198] to-[#e47e8e]"], ["Focus & Study", "24 morceaux · Concentration", "from-[#327a96] to-[#142438]"], ["Night Drive", "37 morceaux · Ambiance nocturne", "from-[#19224a] to-[#7d428b]"]];

function Icon({ name }) { const common = { className: "h-5 w-5", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", strokeWidth: "1.8" }; const icons = { Accueil: <path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1V10Z" />, Recherche: <><circle cx="11" cy="11" r="6.5" /><path d="m16 16 4.5 4.5" /></>, Bibliothèque: <rect x="4" y="3" width="16" height="18" rx="2" />, Découvrir: <><circle cx="12" cy="12" r="9" /><path d="m15.5 8.5-2.2 4.8-4.8 2.2 2.2-4.8 4.8-2.2Z" /></>, Favoris: <path d="M20.8 8.8c0 5.1-8.8 10.2-8.8 10.2S3.2 13.9 3.2 8.8A4.8 4.8 0 0 1 12 6a4.8 4.8 0 0 1 8.8 2.8Z" />, Amis: <><circle cx="9" cy="8" r="3" /><path d="M3.5 20c.4-3.4 2.3-5 5.5-5s5.1 1.6 5.5 5" /></>, Statistiques: <path d="M4 20V11M10 20V4M16 20v-7M22 20V8" /> }; return <svg {...common}>{icons[name]}</svg>; }
function Cover({ gradient, className = "" }) { return <div className={`relative overflow-hidden rounded-lg bg-gradient-to-br ${gradient} ${className}`}><div className="absolute -right-5 -top-5 h-24 w-24 rounded-full border-[15px] border-white/15" /><div className="absolute inset-x-0 bottom-0 h-1/2 bg-black/20" /></div>; }

export default function PlaylistsPage() { return <main className="min-h-screen bg-black text-[#edf0ff] lg:flex">
  <aside className="sticky top-[70px] hidden h-[calc(100dvh-70px)] w-64 shrink-0 self-start overflow-y-auto border-r border-[#5d72fe]/20 bg-[#03050b] px-7 py-6 lg:flex lg:flex-col"><Link href="/" className="mb-9 flex items-center gap-3"><Image src="/logoAudiva2.png" alt="Audiva" width={1254} height={1254} className="h-12 w-12 rounded-xl object-cover" /><span className="text-2xl font-semibold">Audi<span className="text-[#5d72fe]">va</span></span></Link><nav className="space-y-1">{navigation.map(([name, href]) => <Link key={name} href={href} className="flex items-center gap-4 rounded-xl px-3 py-3 text-sm text-[#b9c2ed] hover:bg-[#5d72fe]/10 hover:text-white"><Icon name={name} />{name}</Link>)}</nav><Link href="/playlists" className="mt-6 flex items-center gap-3 rounded-xl bg-[#5d72fe] px-3 py-3 text-sm font-semibold">☷ Mes playlists</Link></aside>
  <div className="min-w-0 flex-1 p-5 sm:p-8"><section className="relative overflow-hidden rounded-xl border border-[#5d72fe]/30 bg-[radial-gradient(circle_at_85%_30%,rgba(93,114,254,0.4),transparent_26%),#080d20] p-7 sm:p-9"><div className="absolute right-10 top-5 hidden h-40 w-40 rounded-full border-[28px] border-[#5d72fe]/25 lg:block" /><p className="text-xs font-semibold uppercase tracking-[0.25em] text-[#aab6f4]">Votre espace musical</p><h1 className="mt-2 text-4xl font-bold">Mes playlists</h1><p className="mt-3 max-w-xl text-sm text-[#b8c2e7]">Créez, organisez et partagez les bandes-son de chaque moment.</p><button className="mt-6 rounded-full bg-[#5d72fe] px-5 py-3 text-sm font-semibold hover:bg-[#7184ff]">＋ Créer une playlist</button></section>
    <div className="mt-8 flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-xl font-semibold">Vos playlists</h2><p className="mt-1 text-xs text-[#8f9bc9]">{playlists.length} playlists disponibles</p></div><div className="flex gap-2"><button className="rounded-full border border-[#5d72fe]/40 px-4 py-2 text-xs">Récentes ▾</button><button className="rounded-full border border-[#5d72fe]/40 px-4 py-2 text-xs">Grille ▦</button></div></div>
    <div className="mt-5 grid grid-cols-2 gap-4 sm:grid-cols-3 xl:grid-cols-4"> <button className="flex aspect-square flex-col items-center justify-center rounded-xl border border-dashed border-[#5d72fe]/55 bg-[#080d1a] text-[#bdc6f5] hover:bg-[#10183a]"><span className="flex h-14 w-14 items-center justify-center rounded-full bg-[#5d72fe] text-4xl font-light text-white">+</span><span className="mt-4 text-sm font-semibold">Nouvelle playlist</span></button>{playlists.map(([title, details, gradient]) => <Link href={`/playlists/${title.toLowerCase().replaceAll(" ", "-")}`} key={title} className="group rounded-xl bg-[#070b18] p-3 transition hover:bg-[#10183a]"><Cover gradient={gradient} className="aspect-square w-full" /><div className="mt-3 flex items-start justify-between gap-2"><div className="min-w-0"><p className="truncate font-semibold">{title}</p><p className="mt-1 truncate text-xs text-[#8f9bc9]">{details}</p></div><span className="text-[#b9c2ed]">•••</span></div></Link>)}</div>
  </div>
</main>; }
