import Image from "next/image";
import Link from "next/link";

const nav = [["Accueil", "/"], ["Recherche", "/recherche"], ["Bibliothèque", "/bibliotheque"], ["Découvrir", "/decouverte"], ["Favoris", "/favoris"], ["Amis", "/amis"], ["Statistiques", "/statistiques"]];
const queue = [["Midnight City", "M83", "from-[#244b9d] to-[#dd9dc4]"], ["Blinding Lights", "The Weeknd", "from-[#d0272b] to-[#151022]"], ["Calm Down", "Rema", "from-[#e3a24b] to-[#654829]"], ["Another Love", "Tom Odell", "from-[#e9917c] to-[#563c64]"]];
function Cover({ gradient, className = "" }) { return <div className={`relative overflow-hidden rounded-xl bg-gradient-to-br ${gradient} ${className}`}><div className="absolute -right-8 -top-8 h-36 w-36 rounded-full border-[22px] border-white/15" /><div className="absolute inset-x-0 bottom-0 h-1/3 bg-black/25" /></div>; }
function Icon({ name }) { const common = { className: "h-5 w-5", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", strokeWidth: "1.8" }; const items = { Accueil: <path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1V10Z" />, Recherche: <><circle cx="11" cy="11" r="6.5" /><path d="m16 16 4.5 4.5" /></>, Bibliothèque: <rect x="4" y="3" width="16" height="18" rx="2" />, Découvrir: <circle cx="12" cy="12" r="9" />, Favoris: <path d="M20.8 8.8c0 5.1-8.8 10.2-8.8 10.2S3.2 13.9 3.2 8.8A4.8 4.8 0 0 1 12 6a4.8 4.8 0 0 1 8.8 2.8Z" />, Amis: <><circle cx="9" cy="8" r="3" /><path d="M3.5 20c.4-3.4 2.3-5 5.5-5s5.1 1.6 5.5 5" /></>, Statistiques: <path d="M4 20V11M10 20V4M16 20v-7M22 20V8" /> }; return <svg {...common}>{items[name]}</svg>; }
export default function LecteurPage() { return <main className="min-h-screen bg-black text-[#edf0ff] lg:flex">
  <aside className="sticky top-[70px] hidden h-[calc(100dvh-70px)] w-64 shrink-0 self-start overflow-y-auto border-r border-[#5d72fe]/20 bg-[#03050b] px-7 py-6 lg:flex lg:flex-col"><Link href="/" className="mb-9 flex items-center gap-3"><Image src="/logoAudiva2.png" alt="Audiva" width={1254} height={1254} className="h-12 w-12 rounded-xl object-cover" /><span className="text-2xl font-semibold">Audi<span className="text-[#5d72fe]">va</span></span></Link><nav className="space-y-1">{nav.map(([name, href]) => <Link key={name} href={href} className={`flex items-center gap-4 rounded-xl px-3 py-3 text-sm ${name === "Accueil" ? "text-[#b9c2ed] hover:bg-[#5d72fe]/10" : "text-[#b9c2ed] hover:bg-[#5d72fe]/10"}`}><Icon name={name} />{name}</Link>)}</nav><Link href="/lecteur" className="mt-6 flex items-center gap-3 rounded-xl bg-[#5d72fe] px-3 py-3 text-sm font-semibold">▶ Lecteur en cours</Link></aside>
  <div className="min-w-0 flex-1 p-5 sm:p-8"><div className="grid gap-6 xl:grid-cols-[minmax(300px,0.9fr)_minmax(360px,1.15fr)_300px]"><section><Cover gradient="from-[#e9917c] via-[#bd6680] to-[#283053]" className="aspect-square w-full max-w-[520px] shadow-2xl" /><div className="mt-6 flex items-center justify-between"><div><h1 className="text-2xl font-bold">Another Love</h1><p className="mt-1 text-sm text-[#9facdf]">Tom Odell · Long Way Down</p></div><button className="text-2xl text-[#8192ff]">♡</button></div></section>
    <section className="flex min-h-[560px] flex-col rounded-xl border border-[#5d72fe]/20 bg-[#070b18] p-6"><p className="text-xs font-semibold uppercase tracking-[0.24em] text-[#9facdf]">Paroles</p><div className="my-auto space-y-5 text-center text-lg font-medium leading-relaxed text-[#67739f]"><p>And I wanna cry, and I wanna love</p><p className="scale-110 text-2xl font-bold text-white">But all my tears have been used up</p><p>On another love, another love</p><p>All my tears have been used up</p></div><button className="text-center text-sm text-[#8192ff]">Afficher toutes les paroles</button></section>
    <aside className="rounded-xl border border-[#5d72fe]/20 bg-[#070b18] p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">File d&apos;attente</h2><button className="text-xs text-[#8192ff]">Effacer</button></div><p className="mt-4 text-xs uppercase tracking-wider text-[#8f9bc9]">À suivre</p><div className="mt-3 space-y-3">{queue.map(([title, artist, gradient], index) => <div key={title} className={`flex items-center gap-3 rounded-lg p-2 ${index === 0 ? "bg-[#5d72fe]/15" : ""}`}><Cover gradient={gradient} className="h-12 w-12" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{title}</p><p className="mt-1 text-xs text-[#8f9bc9]">{artist}</p></div><span className="text-[#aab5e5]">•••</span></div>)}</div></aside></div>
    <section className="mt-7 rounded-xl border border-[#5d72fe]/25 bg-[#080d20] px-5 py-5"><div className="flex items-center justify-between text-xs text-[#aeb8df]"><span>1:42</span><span>4:04</span></div><div className="mt-2 h-1.5 rounded-full bg-[#242e58]"><div className="h-full w-[42%] rounded-full bg-[#5d72fe]" /></div><div className="mt-6 flex items-center justify-center gap-7"><button className="text-xl text-[#aeb8df]">↔</button><button className="text-xl">|◀</button><button className="flex h-14 w-14 items-center justify-center rounded-full bg-[#5d72fe] text-xl">❚❚</button><button className="text-xl">▶|</button><button className="text-xl text-[#aeb8df]">↻</button></div></section>
  </div></main>; }
