"use client";

import Image from "next/image";
import Link from "next/link";
import { Suspense, useEffect, useMemo, useRef, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { HugeiconsIcon } from "@hugeicons/react";
import { Add01Icon, Cancel01Icon, ChartBarBigIcon, Clock01Icon, Delete02Icon, FavouriteIcon, FileMusicIcon, LibraryIcon, MoreHorizontalIcon, MusicNote01Icon, PlayIcon, Queue01Icon, Search01Icon, Upload01Icon } from "@hugeicons/core-free-icons";
import CreatePlaylistButton from "@/domaines/playlists/composants/CreatePlaylistButton";
import AddToPlaylistModal from "@/composants/ui/AddToPlaylistModal";
import { useBibliothequeStore } from "@/domaines/bibliotheque/stores/bibliothequeStore";
import { demoQueue, useLecteurStore } from "@/domaines/lecteur/stores/lecteurStore";
import { usePlaylistsStore } from "@/domaines/playlists/stores/playlistsStore";
import { deleteLocalTrack, loadLocalTracks, saveLocalTracks } from "@/utilitaires/bibliothequeLocaleStorage";

const tabs = [{ id: "titres", label: "Titres", icon: MusicNote01Icon }, { id: "playlists", label: "Playlists", icon: LibraryIcon }, { id: "historique", label: "Historique", icon: Clock01Icon }, { id: "statistiques", label: "Statistiques", icon: ChartBarBigIcon }];
const playlistCards = [{ id: "blue-hour", title: "Blue Hour", description: "Une sélection nocturne pour ralentir.", cover: "/hero-recommandation.jpg", tracks: 18 }, { id: "nuit-electrique", title: "Nuit électrique", description: "Synthés, énergie et bonnes vibrations.", cover: "/hero-playlist.jpg", tracks: 24 }, { id: "jamendo", title: "Découvertes Jamendo", description: "Les voix indépendantes à suivre.", cover: "/hero-decouverte.jpg", tracks: 16 }, { id: "afro-future", title: "Afro Future", description: "Les sons partagés par la communauté.", cover: "/hero-tendances.jpg", tracks: 22 }];
const supportedTypes = ["audio/mpeg", "audio/mp3", "audio/wav", "audio/x-wav", "audio/ogg", "audio/mp4", "audio/aac", "audio/flac"];

export default function BibliothequePage() { return <Suspense fallback={<Fallback />}><LibraryRoute /></Suspense>; }
function LibraryRoute() { const params = useSearchParams(); const view = tabs.some((tab) => tab.id === params.get("vue")) ? params.get("vue") : "titres"; return <Library view={view} initiallyOpen={params.get("import") === "1"} />; }

function Library({ view: initialView, initiallyOpen }) {
  const router = useRouter(); const fileInput = useRef(null);
  const [view, setView] = useState(initialView), [query, setQuery] = useState(""), [scope, setScope] = useState("Tous les titres"), [menuId, setMenuId] = useState(null), [importOpen, setImportOpen] = useState(initiallyOpen), [playlistTarget, setPlaylistTarget] = useState(null), [notice, setNotice] = useState("");
  const [sort, setSort] = useState("added");
  const { tracks: localTracks, addTracks, removeTrack, setTracks } = useBibliothequeStore();
  const player = useLecteurStore(); const restoreLocalTracks = useLecteurStore((state) => state.restoreLocalTracks); const addTrackToPlaylist = usePlaylistsStore((state) => state.addTrack); const allTracks = useMemo(() => [...localTracks, ...demoQueue], [localTracks]);
  useEffect(() => { if (!initiallyOpen) return undefined; const timer = window.setTimeout(() => setImportOpen(true), 0); return () => window.clearTimeout(timer); }, [initiallyOpen]);
  const tracks = useMemo(() => [...allTracks.filter((track) => `${track.title} ${track.artist} ${track.album || ""}`.toLowerCase().includes(query.toLowerCase()) && (scope === "Tous les titres" || track.source === "local"))].sort((a, b) => sort === "title" ? a.title.localeCompare(b.title) : sort === "artist" ? a.artist.localeCompare(b.artist) : (b.addedAt || 0) - (a.addedAt || 0)), [allTracks, query, scope, sort]);
  useEffect(() => { const search = document.querySelector('input[placeholder="Filtrer votre bibliothèque"]'); const parent = search?.parentElement; if (!parent) return undefined; const select = document.createElement("select"); select.className = "h-11 border border-white/10 bg-[#0c1425] px-3 text-xs font-bold text-[#c7d2e7] outline-none"; select.setAttribute("aria-label", "Trier les titres"); select.innerHTML = '<option value="added">Date d’ajout</option><option value="title">Titre</option><option value="artist">Artiste</option>'; const onChange = () => setSort(select.value); select.addEventListener("change", onChange); parent.insertAdjacentElement("afterend", select); return () => { select.removeEventListener("change", onChange); select.remove(); }; }, []);
  useEffect(() => { if (view !== "statistiques") return undefined; const heading = Array.from(document.querySelectorAll("h2")).find((node) => node.textContent === "Statistiques d’écoute"); const host = heading?.closest("div")?.parentElement; if (!host) return undefined; const panel = document.createElement("section"); panel.className = "mt-5 border border-white/[.08] bg-[#0a1221] p-5"; panel.innerHTML = '<div class="flex flex-wrap items-center justify-between gap-3"><div><p class="text-xs font-bold uppercase tracking-[.12em] text-[#83eee8]">Comparaison avec vos amis</p><p class="mt-2 text-sm font-extrabold text-white">Vos goûts musicaux se rapprochent de Sophie N.</p></div><select class="border border-white/12 bg-[#07101e] px-3 py-2 text-xs font-bold text-white"><option>Sophie N.</option><option>Julie R.</option><option>Marc T.</option></select></div><div class="mt-5 grid grid-cols-3 gap-3 text-center"><div><b class="block text-2xl text-[#72eee7]">86 %</b><span class="text-[11px] text-[#91a0bd]">compatibilité</span></div><div><b class="block text-2xl text-white">7</b><span class="text-[11px] text-[#91a0bd]">artistes communs</span></div><div><b class="block text-2xl text-white">3 h 24</b><span class="text-[11px] text-[#91a0bd]">écoute cette semaine</span></div></div>'; host.appendChild(panel); return () => panel.remove(); }, [view]);
  const recent = useMemo(() => player.queue.slice(0, Math.max(0, player.currentIndex)).reverse(), [player.queue, player.currentIndex]);
  const notify = (message) => { setNotice(message); window.setTimeout(() => setNotice(""), 2400); };
  useEffect(() => { let active = true; const timer = window.setTimeout(() => { loadLocalTracks().then((stored) => { if (!active) return; setTracks(stored); restoreLocalTracks(stored); }).catch(() => { if (active) notify("Impossible de restaurer les fichiers locaux"); }); }, 0); return () => { active = false; window.clearTimeout(timer); }; }, [setTracks, restoreLocalTracks]);
  const go = (next) => { setView(next); router.replace(`/bibliotheque?vue=${next}`); };
  const closeImport = () => { setImportOpen(false); router.replace(`/bibliotheque?vue=${view}`); };
  const launch = (track) => { if (player.currentTrack?.id === track.id && player.isPlaying) player.pause(); else { player.setCurrentTrack(track); player.play(); } };
  const playTracks = (items, message) => { if (!items.length) return; player.setQueue(items); player.setCurrentTrack(items[0]); player.play(); notify(message); };
  const removeImported = async (track) => { removeTrack(track.id); URL.revokeObjectURL(track.streamUrl); try { await deleteLocalTrack(track.id); notify("Fichier retiré de la bibliothèque"); } catch { notify("Le fichier a été retiré, mais sa copie locale n’a pas pu être supprimée"); } };
  const importFiles = async (files) => {
    const accepted = Array.from(files).filter((file) => supportedTypes.includes(file.type) || /\.(mp3|wav|ogg|m4a|aac|flac)$/i.test(file.name));
    if (!accepted.length) return notify("Choisissez un fichier audio compatible");
    const additions = await Promise.all(accepted.map(async (file, index) => { const streamUrl = URL.createObjectURL(file); const duration = await audioDuration(streamUrl); return { id: `local-${file.name}-${file.lastModified}-${file.size}`, title: file.name.replace(/\.[^/.]+$/, "").replaceAll("_", " "), artist: "Fichier local", album: "Ma bibliothèque", cover: playlistCards[index % playlistCards.length].cover, duration, streamUrl, source: "local", addedAt: Date.now(), file }; }));
    try { await saveLocalTracks(additions); addTracks(additions.map(({ file, ...track }) => track)); closeImport(); notify(`${additions.length} titre${additions.length > 1 ? "s" : ""} ajouté${additions.length > 1 ? "s" : ""}`); } catch { notify("L’import a échoué : vérifiez l’espace disponible sur cet appareil"); }
  };
  return <main className="min-h-screen bg-[#060b18] pb-32 text-[#eff4ff]"><Hero localTracks={localTracks} trackCount={allTracks.length} onPlay={() => playTracks(tracks, "Bibliothèque chargée dans le lecteur")} onImport={() => setImportOpen(true)} /><section className="mx-auto w-full max-w-[1500px] px-4 py-8 sm:px-7 xl:px-9"><nav className="flex flex-wrap gap-2 border-b border-white/[.08] pb-4">{tabs.map((tab) => <button type="button" key={tab.id} onClick={() => go(tab.id)} className={`inline-flex items-center gap-2 px-4 py-2.5 text-sm font-extrabold transition ${view === tab.id ? "bg-[#72eee7] text-[#061426]" : "text-[#aebad0] hover:bg-white/[.06] hover:text-white"}`}><HugeiconsIcon icon={tab.icon} size={18} strokeWidth={2.2} />{tab.label}</button>)}</nav>{view === "titres" && <Tracks tracks={tracks} scope={scope} setScope={setScope} query={query} setQuery={setQuery} player={player} menuId={menuId} setMenuId={setMenuId} onLaunch={launch} onDelete={removeImported} onAddToPlaylist={setPlaylistTarget} onNotice={notify} />}{view === "playlists" && <Playlists onPlay={(playlist) => playTracks(Array.isArray(playlist.tracks) ? playlist.tracks : demoQueue, `Lecture de « ${playlist.title} »`)} />}{view === "historique" && <History tracks={recent} current={player.currentTrack} onLaunch={launch} />}{view === "statistiques" && <Statistics total={allTracks.length} imported={localTracks.length} liked={player.likedTrackIds.length} recent={recent.length} onHistory={() => go("historique")} />}</section>{importOpen && <ImportDialog inputRef={fileInput} onClose={closeImport} onImport={importFiles} />}{playlistTarget && <AddToPlaylistModal isOpen onClose={() => setPlaylistTarget(null)} onAddToPlaylist={(playlist) => { addTrackToPlaylist(playlist.id, playlistTarget); notify(`« ${playlistTarget.title} » a été ajouté à « ${playlist.title} »`); }} />}{notice && <p role="status" className="fixed bottom-24 right-5 z-[80] border border-[#72eee7]/30 bg-[#112139] px-4 py-3 text-sm font-bold text-[#c8fffb] shadow-2xl">{notice}</p>}</main>;
}

function Hero({ localTracks, trackCount, onPlay, onImport }) { return <section className="relative isolate overflow-hidden border-b border-white/[.07] bg-[#081122] px-5 pb-10 pt-11 sm:px-10 lg:px-14"><Image src="/hero-playlist.jpg" alt="" fill priority className="-z-20 scale-[1.04] object-cover opacity-55" /><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_74%_18%,rgba(75,117,255,.27),transparent_35%),linear-gradient(90deg,#060b18_3%,rgba(6,11,24,.7)_47%,rgba(6,11,24,.2)),linear-gradient(180deg,transparent_42%,#060b18)]" /><div className="relative mx-auto flex max-w-[1500px] flex-col justify-end gap-7 sm:min-h-[280px] sm:flex-row sm:items-end sm:justify-between"><div className="flex items-end gap-5"><div className="grid h-28 w-28 shrink-0 place-items-center bg-[#102044] shadow-[0_18px_40px_rgba(0,0,0,.4)] sm:h-36 sm:w-36"><HugeiconsIcon icon={LibraryIcon} size={50} strokeWidth={1.65} className="text-[#72eee7]" /></div><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-[#83eee8]">Votre collection personnelle</p><h1 className="mt-2 text-4xl font-black tracking-[-.055em] text-white sm:text-6xl">Ma bibliothèque</h1><p className="mt-3 text-sm font-medium text-[#c1cce3]"><b className="text-white">{localTracks.length}</b> fichier{localTracks.length !== 1 ? "s" : ""} local{localTracks.length !== 1 ? "aux" : ""} · {trackCount} titres disponibles</p></div></div><div className="flex flex-wrap gap-2"><button type="button" onClick={onPlay} className="inline-flex items-center gap-2 bg-[#72eee7] px-5 py-3 text-sm font-extrabold text-[#061426] transition hover:scale-[1.03] hover:bg-white"><HugeiconsIcon icon={PlayIcon} size={19} fill="currentColor" />Lire ma bibliothèque</button><button type="button" onClick={onImport} className="inline-flex items-center gap-2 border border-white/20 bg-white/[.08] px-5 py-3 text-sm font-extrabold text-white backdrop-blur transition hover:border-[#72eee7]/50 hover:bg-white/[.15]"><HugeiconsIcon icon={Upload01Icon} size={19} strokeWidth={2.4} />Importer mes fichiers</button></div></div></section>; }

function Tracks({ tracks, scope, setScope, query, setQuery, player, menuId, setMenuId, onLaunch, onDelete, onNotice }) { return <div className="pt-7"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex gap-2">{["Tous les titres", "Importés"].map((item) => <button type="button" key={item} onClick={() => setScope(item)} className={`px-4 py-2 text-xs font-bold ${scope === item ? "bg-[#72eee7] text-[#061426]" : "border border-white/10 bg-white/[.035] text-[#aebad0]"}`}>{item}</button>)}</div><label className="flex h-11 w-full items-center gap-2 border border-white/10 bg-[#0c1425] px-3 text-[#91a0bf] lg:w-72"><HugeiconsIcon icon={Search01Icon} size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Filtrer votre bibliothèque" className="min-w-0 flex-1 bg-transparent text-sm text-white outline-none" /></label></div><div className="mt-7 overflow-hidden border border-white/[.08] bg-[#0a1221]"><div className="grid grid-cols-[34px_minmax(190px,1.5fr)_minmax(110px,1fr)_68px_36px] border-b border-white/[.08] px-4 py-3 text-[10px] font-bold uppercase tracking-[.15em] text-[#72809d]"><span>#</span><span>Titre</span><span className="hidden sm:block">Album</span><span>Durée</span><span /></div>{tracks.length ? tracks.map((track, index) => <Track key={track.id} track={track} index={index} player={player} menuOpen={menuId === track.id} onMenu={() => setMenuId(menuId === track.id ? null : track.id)} onMenuClose={() => setMenuId(null)} onLaunch={() => onLaunch(track)} onDelete={() => onDelete(track)} onNotice={onNotice} />) : <Empty icon={FileMusicIcon} title="Aucun titre ici" text="Importez vos fichiers audio ou modifiez votre filtre." />}</div></div>; }

function Track({ track, index, player, menuOpen, onMenu, onMenuClose, onLaunch, onDelete, onNotice }) { const active = player.currentTrack?.id === track.id && player.isPlaying; const liked = player.likedTrackIds.includes(track.id); const duration = track.duration ? `${Math.floor(track.duration / 60)}:${String(Math.floor(track.duration % 60)).padStart(2, "0")}` : "—"; return <div className={`group grid grid-cols-[34px_minmax(190px,1.5fr)_minmax(110px,1fr)_68px_36px] items-center px-4 py-2.5 hover:bg-white/[.055] ${active ? "bg-[#11284a]/65" : ""}`}><span className="text-sm font-bold text-[#7886a3]">{active ? <HugeiconsIcon icon={PlayIcon} size={15} fill="currentColor" className="text-[#72eee7]" /> : index + 1}</span><button type="button" onClick={onLaunch} className="flex min-w-0 items-center gap-3 text-left"><span className="relative h-11 w-11 shrink-0 overflow-hidden"><Image src={track.cover} alt="" fill sizes="44px" className="object-cover" /></span><span className="min-w-0"><span className={`block truncate text-sm font-bold ${active ? "text-[#72eee7]" : "text-white"}`}>{track.title}</span><span className="block truncate text-xs text-[#91a0bd]">{track.artist}</span></span></button><span className="hidden truncate text-xs text-[#9caac4] sm:block">{track.album}</span><span className="text-xs text-[#8492ad]">{duration}</span><div className="relative flex justify-end"><button type="button" onClick={onMenu} className="grid h-8 w-8 place-items-center text-[#94a2bd] opacity-0 group-hover:opacity-100 focus:opacity-100"><HugeiconsIcon icon={MoreHorizontalIcon} size={19} /></button>{menuOpen && <div className="absolute right-0 top-9 z-20 w-48 border border-white/12 bg-[#151d2d] py-1.5 shadow-2xl"><button type="button" onClick={() => { player.toggleLike(track); onNotice(liked ? "Retiré des favoris" : "Ajouté aux favoris"); onMenuClose(); }} className="flex w-full items-center gap-2 px-3 py-2.5 text-left text-xs font-bold hover:bg-white/[.07]"><HugeiconsIcon icon={FavouriteIcon} size={17} fill={liked ? "currentColor" : "none"} />{liked ? "Retirer des favoris" : "Ajouter aux favoris"}</button><button type="button" onClick={() => { player.addToQueue(track); onNotice("Ajouté à la file d’attente"); onMenuClose(); }} className="flex w-full items-center gap-2 px-3 py-2.5 text-left text-xs font-bold hover:bg-white/[.07]"><HugeiconsIcon icon={Queue01Icon} size={17} />Ajouter à la file</button>{track.source === "local" && <button type="button" onClick={() => { onDelete(); onMenuClose(); }} className="flex w-full items-center gap-2 px-3 py-2.5 text-left text-xs font-bold text-rose-200 hover:bg-rose-400/10"><HugeiconsIcon icon={Delete02Icon} size={17} />Retirer le fichier</button>}</div>}</div></div>; }

function Playlists({ onPlay }) { const userPlaylists = usePlaylistsStore((state) => state.playlists); const cards = [...userPlaylists, ...playlistCards]; return <div className="pt-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[11px] font-bold uppercase tracking-[.15em] text-[#83eee8]">Vos univers sonores</p><h2 className="mt-2 text-3xl font-black text-white">Mes playlists</h2><p className="mt-2 text-sm text-[#91a0bd]">Créez, organisez et partagez vos sélections depuis votre bibliothèque.</p></div><CreatePlaylistButton /></div><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map((playlist) => { const count = Array.isArray(playlist.tracks) ? playlist.tracks.length : playlist.tracks; return <article key={playlist.id} className="group overflow-hidden border border-white/[.08] bg-[#0a1221] p-3 transition hover:-translate-y-1 hover:border-[#72eee7]/35"><Link href={`/playlists/${playlist.id}`} className="relative block aspect-square overflow-hidden"><Image src={playlist.cover || "/hero-playlist.jpg"} alt="" fill sizes="(min-width:1280px) 20vw, 45vw" className="object-cover transition duration-500 group-hover:scale-105" /></Link><div className="mt-4 flex items-start gap-2"><Link href={`/playlists/${playlist.id}`} className="min-w-0 flex-1"><h3 className="truncate text-base font-extrabold text-white">{playlist.title}</h3><p className="mt-1 min-h-10 text-xs leading-5 text-[#91a0bd]">{playlist.description}</p><p className="mt-3 text-[11px] font-bold text-[#72eee7]">{count || 0} morceaux</p></Link><button type="button" onClick={() => onPlay(playlist)} className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#72eee7] text-[#061426] opacity-0 transition group-hover:opacity-100"><HugeiconsIcon icon={PlayIcon} size={19} fill="currentColor" /></button></div></article>; })}</div></div>; }

function History({ tracks, current, onLaunch }) { return <div className="pt-7"><p className="text-[11px] font-bold uppercase tracking-[.15em] text-[#83eee8]">Votre activité</p><h2 className="mt-2 text-3xl font-black text-white">Historique d’écoute</h2><p className="mt-2 text-sm text-[#91a0bd]">Retrouvez les titres lus pendant cette session.</p>{tracks.length ? <div className="mt-7 overflow-hidden border border-white/[.08] bg-[#0a1221]">{tracks.map((track, index) => <button type="button" key={`${track.id}-${index}`} onClick={() => onLaunch(track)} className="flex w-full items-center gap-4 border-b border-white/[.06] px-4 py-3 text-left hover:bg-white/[.045]"><span className="text-xs font-bold text-[#7685a2]">{String(index + 1).padStart(2, "0")}</span><span className="relative h-12 w-12 shrink-0 overflow-hidden"><Image src={track.cover} alt="" fill sizes="48px" className="object-cover" /></span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-extrabold text-white">{track.title}</span><span className="block truncate text-xs text-[#91a0bd]">{track.artist} · {track.album}</span></span>{current?.id === track.id && <span className="text-[10px] font-bold uppercase text-[#72eee7]">En cours</span>}<HugeiconsIcon icon={PlayIcon} size={18} fill="currentColor" /></button>)}</div> : <div className="mt-7"><Empty icon={Clock01Icon} title="Votre historique est vide" text="Les morceaux lus apparaîtront ici pendant votre session d’écoute." /></div>}</div>; }

function Statistics({ total, imported, liked, recent, onHistory }) { const stats = [["Titres disponibles", total, "dans votre collection"], ["Fichiers importés", imported, "sur cet appareil"], ["Favoris", liked, "titres aimés"], ["Écoutés récemment", recent, "cette session"]]; return <div className="pt-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[11px] font-bold uppercase tracking-[.15em] text-[#83eee8]">Votre bilan Audiva</p><h2 className="mt-2 text-3xl font-black text-white">Statistiques d’écoute</h2><p className="mt-2 text-sm text-[#91a0bd]">Un aperçu personnel connecté à votre bibliothèque.</p></div><button type="button" onClick={onHistory} className="border border-white/12 bg-white/[.04] px-4 py-2.5 text-sm font-bold hover:border-[#72eee7]/45">Voir l’historique</button></div><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([label, value, hint]) => <article key={label} className="border border-white/[.08] bg-[#0a1221] p-5"><p className="text-xs font-bold uppercase tracking-[.12em] text-[#91a0bd]">{label}</p><p className="mt-4 text-4xl font-black text-white">{value}</p><p className="mt-2 text-xs text-[#72eee7]">{hint}</p></article>)}</div><div className="mt-5 border border-white/[.08] bg-[#0a1221] p-6"><p className="text-sm font-extrabold text-white">Votre rythme d’écoute</p><div className="mt-6 flex h-24 items-end gap-2">{[38, 62, 47, 79, 55, 92, 69].map((height, index) => <span key={index} className="flex-1 bg-[#72eee7]/20"><span className="block w-full bg-[#72eee7]" style={{ height: `${height}%` }} /></span>)}</div></div></div>; }

function Empty({ icon, title, text }) { return <div className="px-6 py-16 text-center"><HugeiconsIcon icon={icon} size={31} className="mx-auto text-[#72eee7]" /><h2 className="mt-4 text-lg font-extrabold text-white">{title}</h2><p className="mx-auto mt-2 max-w-md text-sm text-[#91a0bd]">{text}</p></div>; }
function ImportDialog({ inputRef, onClose, onImport }) { const [dragging, setDragging] = useState(false); return <div role="dialog" aria-modal="true" className="fixed inset-0 z-[90] grid place-items-center bg-[#02050b]/80 p-4 backdrop-blur-sm" onMouseDown={onClose}><div className="w-full max-w-xl border border-white/12 bg-[#0d1527] p-6 shadow-2xl" onMouseDown={(event) => event.stopPropagation()}><div className="flex justify-between"><div><HugeiconsIcon icon={Upload01Icon} size={25} className="text-[#72eee7]" /><h2 className="mt-3 text-xl font-extrabold">Importer ma musique</h2><p className="mt-1 text-sm text-[#9eabc4]">Vos fichiers restent locaux à cet appareil.</p></div><button type="button" onClick={onClose} className="h-9 w-9"><HugeiconsIcon icon={Cancel01Icon} size={20} /></button></div><input ref={inputRef} type="file" accept="audio/*,.flac,.aac" multiple className="sr-only" onChange={(event) => onImport(event.target.files)} /><button type="button" onClick={() => inputRef.current?.click()} onDragOver={(event) => { event.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={(event) => { event.preventDefault(); setDragging(false); onImport(event.dataTransfer.files); }} className={`mt-6 flex min-h-52 w-full flex-col items-center justify-center border border-dashed p-6 ${dragging ? "border-[#72eee7] bg-[#72eee7]/10" : "border-white/18 bg-[#07101e]"}`}><HugeiconsIcon icon={FileMusicIcon} size={34} className="text-[#72eee7]" /><p className="mt-4 font-extrabold">Glissez vos fichiers audio ici</p><p className="mt-2 text-xs text-[#91a0bd]">ou cliquez pour choisir des fichiers MP3, WAV, OGG, M4A, AAC ou FLAC</p><span className="mt-5 inline-flex items-center gap-2 bg-[#72eee7] px-4 py-2.5 text-xs font-extrabold text-[#061426]"><HugeiconsIcon icon={Add01Icon} size={16} />Choisir des fichiers</span></button></div></div>; }
function audioDuration(url) { return new Promise((resolve) => { const audio = new Audio(); audio.onloadedmetadata = () => resolve(Number.isFinite(audio.duration) ? Math.round(audio.duration) : 0); audio.onerror = () => resolve(0); audio.src = url; }); }
function Fallback() { return <main className="min-h-screen bg-[#060b18] p-10"><div className="h-72 animate-pulse bg-[#0b1426]" /></main>; }
