import Image from "next/image";
import Link from "next/link";

const navigation = ["Accueil", "Recherche", "Bibliothèque", "Découvrir", "Favoris", "Amis", "Statistiques"];
const routes = { Accueil: "/", Recherche: "/recherche", Bibliothèque: "/bibliotheque", Découvrir: "/decouverte", Favoris: "/favoris", Amis: "/amis", Statistiques: "/statistiques" };
const tracks = [["Blinding Lights", "The Weeknd", "After Hours", "3:20", "from-[#d0272b] to-[#151022]"], ["Another Love", "Tom Odell", "Long Way Down", "4:04", "from-[#e9917c] to-[#563c64]"], ["Calm Down", "Rema, Selena Gomez", "Rave & Roses", "3:59", "from-[#e3a24b] to-[#654829]"], ["Flowers", "Miley Cyrus", "Endless Summer Vacation", "3:20", "from-[#81bfcc] to-[#d6c68e]"], ["As It Was", "Harry Styles", "Harry's House", "2:47", "from-[#d8818b] to-[#39555c]"], ["Last Last", "Burna Boy", "Love, Damini", "2:52", "from-[#cf7742] to-[#2d1d1d]"]];
const albums = [["After Hours", "The Weeknd", "from-[#d0272b] to-[#151022]"], ["Love, Damini", "Burna Boy", "from-[#e66e36] to-[#3a2020]"], ["Harry's House", "Harry Styles", "from-[#eab876] to-[#477374]"], ["SOS", "SZA", "from-[#318fd0] to-[#d6d9de]"]];

function Icon({ name }) { const common = { className: "h-5 w-5", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", strokeWidth: "1.8" }; const icons = { Accueil: <path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1V10Z" />, Recherche: <><circle cx="11" cy="11" r="6.5" /><path d="m16 16 4.5 4.5" /></>, Bibliothèque: <><rect x="4" y="3" width="16" height="18" rx="2" /><path d="M8 3v5l2-1.5L12 8V3" /></>, Découvrir: <><circle cx="12" cy="12" r="9" /><path d="m15.5 8.5-2.2 4.8-4.8 2.2 2.2-4.8 4.8-2.2Z" /></>, Favoris: <path d="M20.8 8.8c0 5.1-8.8 10.2-8.8 10.2S3.2 13.9 3.2 8.8A4.8 4.8 0 0 1 12 6a4.8 4.8 0 0 1 8.8 2.8Z" />, Amis: <><circle cx="9" cy="8" r="3" /><path d="M3.5 20c.4-3.4 2.3-5 5.5-5s5.1 1.6 5.5 5M17 9a2.5 2.5 0 1 0 0-5M17 15c2.1 0 3.3 1.1 3.7 3.2" /></>, Statistiques: <path d="M4 20V11M10 20V4M16 20v-7M22 20V8" /> }; return <svg {...common}>{icons[name]}</svg>; }
function Cover({ gradient, className = "" }) { return <div className={`relative shrink-0 overflow-hidden rounded-md bg-gradient-to-br ${gradient} ${className}`}><div className="absolute -right-4 -top-5 h-16 w-16 rounded-full border-[10px] border-white/15" /><div className="absolute inset-x-0 bottom-0 h-1/3 bg-black/25" /></div>; }

export default function BibliothequePage() { return <main className="min-h-screen bg-black text-[#edf0ff] lg:flex">
  <aside className="sticky top-[70px] hidden h-[calc(100dvh-70px)] w-64 shrink-0 self-start overflow-y-auto border-r border-[#5d72fe]/20 bg-[#03050b] px-7 py-6 lg:flex lg:flex-col"><Link href="/" className="mb-9 flex items-center gap-3"><Image src="/logoAudiva2.png" alt="Audiva" width={1254} height={1254} className="h-12 w-12 rounded-xl object-cover" /><span className="text-2xl font-semibold tracking-tight">Audi<span className="text-[#5d72fe]">va</span></span></Link><nav className="space-y-1">{navigation.map((item) => <Link key={item} href={routes[item]} className={`flex items-center gap-4 rounded-xl px-3 py-3 text-sm ${item === "Bibliothèque" ? "bg-[#5d72fe] font-semibold text-white" : "text-[#b9c2ed] hover:bg-[#5d72fe]/10 hover:text-white"}`}><Icon name={item} />{item}</Link>)}</nav><button className="mt-7 rounded-xl border border-dashed border-[#5d72fe]/50 px-3 py-3 text-sm text-[#afbbf2] hover:bg-[#5d72fe]/10">＋ Importer des fichiers</button></aside>
  <div className="min-w-0 flex-1 p-5 sm:p-8"><section className="relative overflow-hidden rounded-xl border border-[#5d72fe]/30 bg-[radial-gradient(circle_at_82%_25%,rgba(93,114,254,0.4),transparent_28%),#080d20] p-6 sm:p-8"><div className="absolute right-5 top-4 hidden h-40 w-40 rounded-full border-[22px] border-[#5d72fe]/25 md:block" /><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#9facf0]">Votre collection</p><h1 className="mt-2 text-3xl font-bold sm:text-4xl">Ma bibliothèque</h1><p className="mt-3 max-w-xl text-sm text-[#b7c0e4]">Retrouvez vos morceaux, albums et fichiers locaux en un seul endroit.</p><div className="mt-6 flex flex-wrap gap-3"><button className="rounded-full bg-[#5d72fe] px-5 py-3 text-sm font-semibold hover:bg-[#7184ff]">▶ Lire ma bibliothèque</button><button className="rounded-full border border-[#5d72fe]/55 px-5 py-3 text-sm text-[#c5cdf3] hover:bg-[#5d72fe]/10">＋ Ajouter des titres</button></div></section>
    <div className="mt-7 flex flex-wrap items-center justify-between gap-3"><nav className="flex rounded-full bg-[#080d1a] p-1 text-sm"><Link href="/bibliotheque" className="rounded-full bg-[#5d72fe] px-4 py-2 font-semibold">Titres</Link><Link href="/bibliotheque/albums" className="rounded-full px-4 py-2 text-[#aab5e5] hover:text-white">Albums</Link><button className="rounded-full px-4 py-2 text-[#aab5e5] hover:text-white">Artistes</button></nav><div className="flex gap-2"><button className="rounded-full border border-[#5d72fe]/35 px-4 py-2 text-xs text-[#bdc6f5]">Filtres ▾</button><button className="rounded-full border border-[#5d72fe]/35 px-4 py-2 text-xs text-[#bdc6f5]">Trier par récent ▾</button></div></div>
    <section className="mt-7"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-xl font-semibold">Récemment ajoutés</h2><p className="mt-1 text-xs text-[#8995c7]">{tracks.length} titres dans votre bibliothèque</p></div><button className="text-sm text-[#8192ff]">Tout afficher →</button></div><div className="overflow-x-auto"><div className="min-w-[700px]"><div className="grid grid-cols-[36px_minmax(220px,1.5fr)_minmax(150px,1fr)_75px_35px] border-b border-white/15 px-2 pb-2 text-[10px] uppercase tracking-wide text-[#8490bf]"><span>#</span><span>Titre</span><span>Album</span><span>Durée</span><span>•••</span></div>{tracks.map(([title, artist, album, duration, gradient], index) => <div key={title} className="grid grid-cols-[36px_minmax(220px,1.5fr)_minmax(150px,1fr)_75px_35px] items-center rounded-md px-2 py-2.5 text-sm hover:bg-[#5d72fe]/10"><span className="text-[#8490bf]">{index + 1}</span><div className="flex min-w-0 items-center gap-3"><Cover gradient={gradient} className="h-11 w-11" /><div className="min-w-0"><p className="truncate font-medium">{title}</p><p className="truncate text-xs text-[#8490bf]">{artist}</p></div></div><span className="truncate text-xs text-[#aeb8df]">{album}</span><span className="text-xs">{duration}</span><button className="text-lg text-[#b9c2ed]">•••</button></div>)}</div></div></section>
    <section className="mt-9"><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-semibold">Albums récemment ajoutés</h2><Link href="/bibliotheque/albums" className="text-sm text-[#8192ff]">Voir les albums →</Link></div><div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">{albums.map(([title, artist, gradient]) => <article key={title} className="rounded-lg bg-[#070b18] p-3 transition hover:bg-[#10183a]"><Cover gradient={gradient} className="aspect-square w-full" /><p className="mt-3 font-medium">{title}</p><p className="mt-1 text-xs text-[#8995c7]">{artist}</p></article>)}</div></section>
  </div>
</main>; }
