"use client";
import Image from "next/image";
import Link from "next/link";
import { HugeiconsIcon } from "@hugeicons/react";
import { Album01Icon, PlayIcon } from "@hugeicons/core-free-icons";
import { demoQueue, useLecteurStore } from "@/domaines/lecteur/stores/lecteurStore";

const albums = [{ id: "blue-hour", title: "Blue Hour", artist: "Maya K.", year: "2026", cover: "/hero-recommandation.jpg", tracks: 12 }, { id: "nuit-electrique", title: "Nuit électrique", artist: "Audiva Sessions", year: "2026", cover: "/hero-playlist.jpg", tracks: 10 }, { id: "afro-future", title: "Afro Future", artist: "Collectif Audiva", year: "2025", cover: "/hero-tendances.jpg", tracks: 14 }, { id: "jamendo-discovery", title: "Jamendo Discovery", artist: "Lila Sun", year: "2025", cover: "/hero-decouverte.jpg", tracks: 9 }];

export default function AlbumsBibliothequePage() { const player = useLecteurStore(); const play = () => { player.setQueue(demoQueue); player.setCurrentTrack(demoQueue[0]); player.play(); }; return <main className="min-h-screen bg-[#060b18] pb-32 text-[#eff4ff]"><section className="relative isolate overflow-hidden px-5 pb-10 pt-12 sm:px-10 lg:px-14"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_76%_5%,rgba(80,128,255,.28),transparent_35%),linear-gradient(135deg,#071120,#0b1730_58%,#060b18)]" /><div className="mx-auto flex max-w-[1500px] items-end gap-5 sm:min-h-[230px]"><div className="grid h-24 w-24 place-items-center bg-[#102044] text-[#72eee7] sm:h-32 sm:w-32"><HugeiconsIcon icon={Album01Icon} size={48} /></div><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-[#83eee8]">Votre collection</p><h1 className="mt-2 text-4xl font-black tracking-[-.055em] text-white sm:text-6xl">Albums</h1><p className="mt-3 text-sm text-[#c1cce3]">Explorez vos albums, leurs morceaux et leurs univers.</p></div></div></section><section className="mx-auto w-full max-w-[1500px] px-4 py-8 sm:px-7 xl:px-9"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{albums.map((album) => <article key={album.id} className="group overflow-hidden border border-white/[.08] bg-[#0a1221] p-3 transition hover:-translate-y-1 hover:border-[#72eee7]/35"><Link href={`/albums/${album.id}`} className="relative block aspect-square overflow-hidden"><Image src={album.cover} alt={`Pochette de ${album.title}`} fill sizes="(min-width:1280px) 22vw, 45vw" className="object-cover transition duration-500 group-hover:scale-105" /></Link><div className="mt-4 flex gap-3"><div className="min-w-0 flex-1"><Link href={`/albums/${album.id}`} className="block truncate text-sm font-extrabold text-white">{album.title}</Link><p className="mt-1 text-xs text-[#91a0bd]">{album.artist} · {album.year}</p><p className="mt-2 text-[11px] font-bold text-[#72eee7]">{album.tracks} morceaux</p></div><button type="button" onClick={play} aria-label={`Lire ${album.title}`} className="grid h-10 w-10 place-items-center rounded-full bg-[#72eee7] text-[#061426]"><HugeiconsIcon icon={PlayIcon} size={19} fill="currentColor" /></button></div></article>)}</div></section></main>; }
