"use client";

import { useMemo, useState } from "react";
import { HugeiconsIcon } from "@hugeicons/react";
import { CheckmarkCircle02Icon, Delete02Icon, Message01Icon, MusicNote01Icon, Notification03Icon, Share01Icon, UserAdd01Icon } from "@hugeicons/core-free-icons";
import { useSocialStore } from "@/domaines/social/stores/socialStore";

export default function NotificationsPage() {
  const [filter, setFilter] = useState("Toutes"); const { notifications: items, markNotificationRead, removeNotification, markAllNotificationsRead } = useSocialStore();
  const unread = items.filter((item) => !item.read).length;
  const shown = useMemo(() => items.filter((item) => filter === "Toutes" || (filter === "Non lues" ? !item.read : item.type === filter)), [items, filter]);
  return <main className="min-h-screen bg-[#060b18] pb-32 text-[#eff4ff]"><Header unread={unread} onAllRead={markAllNotificationsRead} /><section className="mx-auto w-full max-w-[1500px] px-4 py-8 sm:px-7 xl:px-9"><div className="flex flex-wrap gap-2 border-b border-white/[.08] pb-5">{["Toutes", "Non lues", "Musique", "Social", "Partage", "Système"].map((label) => <button type="button" key={label} onClick={() => setFilter(label)} className={`px-4 py-2 text-xs font-extrabold transition ${filter === label ? "bg-[#72eee7] text-[#061426]" : "border border-white/10 bg-white/[.035] text-[#aebad0] hover:border-[#72eee7]/35 hover:text-white"}`}>{label}</button>)}</div><div className="mt-6 overflow-hidden border border-white/[.08] bg-[#0a1221]">{shown.length ? shown.map((notification) => <Row key={notification.id} item={notification} onRead={() => markNotificationRead(notification.id)} onDelete={() => removeNotification(notification.id)} />) : <Empty />}</div></section></main>;
}

function Header({ unread, onAllRead }) { return <section className="relative isolate overflow-hidden border-b border-white/[.07] bg-[#081122] px-5 pb-10 pt-12 sm:px-10 lg:px-14"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_80%_10%,rgba(91,114,255,.34),transparent_31%),linear-gradient(135deg,#071120,#0b1730_58%,#060b18)]" /><div className="mx-auto flex max-w-[1500px] flex-col justify-end gap-6 sm:min-h-[230px] sm:flex-row sm:items-end sm:justify-between"><div className="flex items-end gap-5"><div className="grid h-24 w-24 place-items-center bg-[#102044] shadow-2xl sm:h-32 sm:w-32"><HugeiconsIcon icon={Notification03Icon} size={47} strokeWidth={1.7} className="text-[#72eee7]" /></div><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-[#83eee8]">Restez connecté</p><h1 className="mt-2 text-4xl font-black tracking-[-.055em] text-white sm:text-6xl">Notifications</h1><p className="mt-3 text-sm text-[#c1cce3]">{unread ? `${unread} nouvelle${unread > 1 ? "s" : ""} activité${unread > 1 ? "s" : ""} pour vous` : "Vous êtes à jour."}</p></div></div><button type="button" onClick={onAllRead} disabled={!unread} className="inline-flex items-center gap-2 border border-white/16 bg-white/[.06] px-4 py-2.5 text-sm font-extrabold transition hover:border-[#72eee7]/55 hover:bg-white/[.12] disabled:opacity-40"><HugeiconsIcon icon={CheckmarkCircle02Icon} size={19} />Tout marquer comme lu</button></div></section>; }
function Row({ item, onRead, onDelete }) { const icon = item.type === "partage" ? Share01Icon : item.type === "musique" ? MusicNote01Icon : item.type === "social" ? UserAdd01Icon : Notification03Icon; return <article className={`group flex gap-4 border-b border-white/[.07] px-4 py-4 last:border-0 hover:bg-white/[.04] ${!item.read ? "bg-[#102044]/35" : ""}`}><div className={`grid h-11 w-11 shrink-0 place-items-center ${item.read ? "bg-white/[.06] text-[#94a2bd]" : "bg-[#72eee7]/12 text-[#72eee7]"}`}><HugeiconsIcon icon={icon} size={21} /></div><button type="button" onClick={onRead} className="min-w-0 flex-1 text-left"><div className="flex gap-3"><p className={`truncate text-sm ${item.read ? "font-bold text-[#d5ddec]" : "font-extrabold text-white"}`}>{item.title}</p>{!item.read && <span className="mt-1.5 h-2 w-2 shrink-0 rounded-full bg-[#72eee7]" />}</div><p className="mt-1 text-sm text-[#91a0bd]">{item.text}</p><p className="mt-2 text-[11px] font-bold text-[#6f7e9d]">{item.time}</p></button><button type="button" onClick={onDelete} aria-label="Supprimer la notification" className="grid h-9 w-9 place-items-center self-center text-[#7c89a2] opacity-0 transition hover:bg-rose-400/10 hover:text-rose-300 group-hover:opacity-100 focus:opacity-100"><HugeiconsIcon icon={Delete02Icon} size={18} /></button></article>; }
function Empty() { return <div className="px-6 py-20 text-center"><HugeiconsIcon icon={Notification03Icon} size={33} className="mx-auto text-[#72eee7]" /><h2 className="mt-4 text-lg font-extrabold">Aucune notification</h2><p className="mt-2 text-sm text-[#91a0bd]">Cette catégorie est calme pour le moment.</p></div>; }
